# Generated by Django 2.0.2 on 2018-03-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=10)),
                ('requestName', models.CharField(max_length=30)),
                ('requestName_kr', models.CharField(max_length=30)),
                ('condition', models.TextField()),
                ('reward', models.TextField()),
            ],
        ),
    ]
