# Generated by Django 2.0.2 on 2018-03-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillType', models.CharField(max_length=30)),
                ('skillName', models.TextField()),
                ('point', models.TextField()),
                ('effect', models.TextField()),
            ],
        ),
    ]
