# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questName', models.CharField(max_length=30)),
                ('questName_kr', models.CharField(max_length=30)),
                ('rating', models.CharField(max_length=8)),
                ('contents', models.CharField(max_length=200, null=True)),
                ('questMap', models.CharField(max_length=10)),
                ('questTime', models.CharField(max_length=5)),
                ('condition_main', models.CharField(max_length=50)),
                ('condition_sub', models.CharField(max_length=50, null=True)),
                ('down_payment', models.IntegerField()),
                ('rewardMoney_main', models.IntegerField()),
                ('rewardMoney_sub', models.IntegerField(null=True)),
                ('reward_main', models.CharField(max_length=300)),
                ('reward_sub', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
