# Generated by Django 2.0 on 2017-12-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questName', models.CharField(max_length=30)),
                ('rating', models.CharField(max_length=8, null=True)),
                ('contents', models.CharField(max_length=200, null=True)),
                ('condition', models.CharField(max_length=50, null=True)),
                ('reward', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
