# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='down_payment',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='quest',
            name='rewardMoney_main',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='quest',
            name='rewardMoney_sub',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
