# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0002_auto_20171228_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='keyQuest',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
