# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-14 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0003_quest_keyquest'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='precedingQuestId',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
