# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-22 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0004_quest_precedingquestid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kariwaza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('kariwazaName', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=5)),
                ('condition', models.CharField(max_length=100)),
            ],
        ),
    ]
