# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-03 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0005_kariwaza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=10)),
                ('requestName', models.CharField(max_length=30)),
                ('requestName_kr', models.CharField(max_length=30)),
                ('condition', models.CharField(max_length=50)),
                ('reward', models.CharField(max_length=100)),
            ],
        ),
    ]
