# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-03 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0006_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='condition',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='reward',
            field=models.TextField(),
        ),
    ]
