# Generated by Django 2.0.2 on 2018-03-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0009_auto_20180302_2056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kariwaza',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
