# Generated by Django 2.0.2 on 2018-03-28 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0010_auto_20180327_2053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
